### ISSUE TITLE
Is this the old HD skins mod that was part of the VoxelModPack?

### ISSUE THREAD

**Issue by ExE-Boss** [MineLittlePony/HDSkins#1]
I’m talking about this:
http://www.voxelmodpack.com/info.html#jump_snc

---

If so, it might be a good idea to put that into the readme.

**Comment by killjoy1221** [comment]
Yes, it is. This isn't quite ready for release, but it's currently bundled with [MineLittlePony](https://github.com/MineLittlePony/MineLittlePony/releases)
