### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by RubyNavy** [MineLittlePony/HDSkins#21]
everytime i try to open the "pony menu" my game open the menu but after it crashes

**Comment by killjoy1221** [comment]
The mod does not work with 1.15.2 yet. Wait for a release or downgrade to 1.15.1.

**Comment by RubyNavy** [comment]
> The mod does not work with 1.15.2 yet. Wait for a release or downgrade to 1.15.1.

ok thanks!
