### ISSUE TITLE
I Cant upload my skin!

### ISSUE THREAD

**Issue by RubyNavy** [MineLittlePony/HDSkins#22]
**i know i need to go in to the "pony Button" in the menu and there go to the "browse" BUT THERES NO BROWSE FOR ME ;-;**

![A](https://user-images.githubusercontent.com/38867121/73307521-1ef31580-41fd-11ea-9859-09d1a5c2f75d.PNG)

**Comment by killjoy1221** [comment]
Duplicate of #21
