### ISSUE TITLE
Cannot locate the .jar file for the mod? Where is it located?

### ISSUE THREAD

**Issue by Game-Log** [MineLittlePony/HDSkins#23]
Ok; so this isn't technically an issue with the mod itself, but I cannot seem to find the mod file itself. Last time i downloaded it, it was with the source code, but this update just seems to have the source code by as the only downloadable option. If possible, can you direct me as to where i can find the HD Skins .jar file?

Sorry if this is not the place to ask this.

**Comment by Sollace** [comment]
Oh, my bad. I forgot to attach it when I did the release. XD

**Comment by Sollace** [comment]
🤔 
![image](https://user-images.githubusercontent.com/6429283/73432317-21fc1c00-434b-11ea-9388-04f04c33798e.png)

**Comment by Sollace** [comment]
Fixed.
