### ISSUE TITLE
Uploading skin failed: sun.security.provider.certpath.suncertpathbuilderexception:unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by MrMonster61** [MineLittlePony/HDSkins#24]
Thx i tried to install "LetsEncryptCraft" and reinstalling HDSkins. And it didnt do anything.

Thank you

**Comment by Sollace** [comment]
I'm going to defer this to @killjoy1221 

I guarantee you, that is what fixes this issue. If it's not working, it's something you did wrong.

**Comment by MrMonster61** [comment]
Thank you but could it be fabric-api? everything else is on version 1.15.2. Fabric-api is showing as 1.15?

**Comment by Sollace** [comment]
No.

You need to install LetsEncryptCraft.

Your mods folder should have: MineLittlePony, HDSkins, Fabric-api, and LetsEncryptCraft.

**Comment by Sollace** [comment]
And yes. You should probably update fabric-api.

**Comment by MrMonster61** [comment]
The mod is LetsEncryptCraft-fabric 1.3.1 is the "1.3.1" Game version or Mod version


And sorry if im being annoying

**Comment by Sollace** [comment]
@MrMonster61 Quick question: did you reinstall Fabricloader recently?

**Comment by Sollace** [comment]
1.3.1 is the mod version. It doesn't actually rely on anything from the game so it can be installed on any one.

**Comment by MrMonster61** [comment]
No? And why. And Thank you

**Comment by Sollace** [comment]
Try reinstalling it and getting the latest version. Seems LetsEncryptCraft (for some reason #killjoy ?) depends on newer version of fabric loader and won't load without it.

**Comment by MrMonster61** [comment]
Ok i will try Thank you

**Comment by MrMonster61** [comment]
Just for note everything else Works perfectly and the mod is great

**Comment by MrMonster61** [comment]
Still nothing After reinstalling fabric and all mods nothing worked

**Comment by MrMonster61** [comment]
I am doing this on my cousins Laptop and he has "Cracked" Minecraft and i dont trust him with my Minecraft Java edition account. Does that effect anything?

**Comment by MrMonster61** [comment]
I just dont know enough about minecraft mods and lounchers

**Comment by killjoy1221** [comment]
Please post your game log. The last run's log should be in .minecraft/logs/latest.log. Post it to a paste site like pastebin or gist.

**Comment by MrMonster61** [comment]
Yes Boss gimi a sec

**Comment by MrMonster61** [comment]
`[
[2020-02-02-7.log.gz](https://github.com/MineLittlePony/HDSkins/files/4144701/2020-02-02-7.log.gz)
](url)`

**Comment by MrMonster61** [comment]
[2020-02-02-7.log](https://github.com/MineLittlePony/HDSkins/files/4144706/2020-02-02-7.log)

**Comment by MrMonster61** [comment]
is this ok?
its the latest game log-10 min

**Comment by MrMonster61** [comment]
i was reinstallin jave every mod and nothing seems to work =/

**Comment by killjoy1221** [comment]
Possibly related this [MCL-1119](https://bugs.mojang.com/browse/MCL-1119).

Try disabling your anti-virus. It's not related to letsencrypt, but with SSL Mojang's certificate not getting loaded.

**Comment by Sollace** [comment]
@killjoy1221 Note also that he mentioned he was using a cracked game.

**Comment by MrMonster61** [comment]
Not me my cousin im doing this for her

**Comment by killjoy1221** [comment]
No he's not.
> i dont trust him with my Minecraft Java edition account.

**Comment by MrMonster61** [comment]
And how do i turn of my "anti-virus" if i dont have one. I use Windows defender?

**Comment by killjoy1221** [comment]
We should confirm if this is the issue first. Can you connect to servers in online mode? If you can't, you should try in vanilla. If it doesn't work in vanilla, you should get support from mojang.

**Comment by Sollace** [comment]
> No he's not.
> 
> > i dont trust him with my Minecraft Java edition account.

Alrighty. He said he was using his cousin's laptop and that his cousin had a cracked game, so i assumed he was using his cousin's game for this.

**Comment by MrMonster61** [comment]
correct

**Comment by MrMonster61** [comment]
im soooo sorry for the confusion

**Comment by ArcAngelica** [comment]
Been having the same issue, this problem only showed up yesterday
By the start of the day the mod worked fine, playing a little after and the problem was in place, no updates, no version changes, no mod changes.

Tried to use LetsEncryptCraft which I didn't have before but the mod still worked, didn't fix
Reinstalled Fabric, API, HDSkins, didn't fix
Disabling anti-virus, didn't fix

I was running the 1.15 version, and it is on a verified client with my verified account
[Log File](https://mega.nz/#!NssHhSAT!8g2WuQLUcQMA3on9Bm757BctNJ45Epsq6frylAiSBGM)

I ironically even recorded it working yesterday, went to edit, by the time I got back to the game the issue was in place, very weird

**Comment by killjoy1221** [comment]
@ArcAngelica You don't have LetsEncryptCraft installed.

**Comment by ArcAngelica** [comment]
It still doesn't change how I didn't need in the first place for it to work at all...

Regardless, apparently I was trying the wrong version of LetsEncryptCraft, I was googling the latest version which a majority of sources said it was v1.2.0, the truly latest version was only linked/mentioned in the notes for the latest release of HDSkins, googling it doesn't actually give you the 1.3.1 version, and the 1.15 release doesn't bring up that you need LetsEncryptCraft

**Comment by MrMonster61** [comment]
So all you are saying is that i

**Comment by MrMonster61** [comment]
shoud insall an older version?

**Comment by MrMonster61** [comment]
And another question shoud all pony villagers have the same texture?

**Comment by Sollace** [comment]
Should be resolved in the latest release. https://github.com/MineLittlePony/HDSkins/releases/tag/v6.1.2-mc1.15.2
