### ISSUE TITLE
Crash when opening skin manager (6.1.1-1.15.2)

### ISSUE THREAD

**Issue by derram** [MineLittlePony/HDSkins#25]
[crash-2020-02-06_15.11.03-client.txt](https://github.com/MineLittlePony/HDSkins/files/4167775/crash-2020-02-06_15.11.03-client.txt)

**Comment by Sollace** [comment]
Seems like people are using a different version of Java than I am, because when I check the location of that stacktrace, HashMap does not throw `ConcurrentModificationException` in `computeIfAbsent`.

**Comment by Sollace** [comment]
Duplicate of https://github.com/MineLittlePony/Mson/issues/3
