### ISSUE TITLE
HDSkins crashes when trying to open

### ISSUE THREAD

**Issue by pastelpalette** [MineLittlePony/HDSkins#26]
https://pastebin.com/FG6U6DAn
java version 13.0.2
java 1.8.0 doesn't crash but I cannot upload a new skin, it just sits at Uploading skin please wait... infinately

**Comment by pastelpalette** [comment]
so far with playing with things, setting java back to older versions with letsencryptcraft allows me to see the pony skin server, but uploading and clearing the skin I'm currently stuck with is an infinite wall of waiting, taking letsencryptcraft out does the typical error, updating java past 1.8.0_241 causes a render error crash regardless of any other mods in the folder along side the minelittlepony and HDSkins jar, so my issue so far is when I solve the crashing error by loading an older java version I cannot change my skin on the MLP skin server and can only change the minecraft server skin, conversely with the java updated when I click the button to enter the skin change menu I simply CTD
all mods are up to date

**Comment by pastelpalette** [comment]
I managed a breakthrough in fixing the crashing on java post 1.8.0, I had to change my resolution from 1920x1080@25 to 1920x1080@60 and some reason that fixed the rendering issues but uploading skins is still a stuck process of infinite loading

**Comment by Sollace** [comment]
Do you have the game log from that infinite loading error? (preferably not using pastebin)

**Comment by Sollace** [comment]
I'm now on wifi and can see the original crash report. The only reason that I can think of which would cause that is if minelp's entrypoint didn't run.

**Comment by Sollace** [comment]
Although not really, because it does seem to be using the dummypony... It must be a resource loading issue.

**Comment by pastelpalette** [comment]
https://pastebin.com/BG5auWbS

**Comment by pastelpalette** [comment]
the crashing issue was fixed by me changing my resolution from 1920x1080@25 to 1920x1080@60 in the minecraft options

**Comment by Sollace** [comment]
@pastelpalette I can't load pastebin. Just upload the log file here.

**Comment by pastelpalette** [comment]
[2020-02-10-7.log.gz](https://github.com/MineLittlePony/HDSkins/files/4188011/2020-02-10-7.log.gz)

**Comment by Sollace** [comment]
@pastelpalette Ok.
![image](https://user-images.githubusercontent.com/6429283/74273979-01a06a00-4d1a-11ea-9864-c5ce8b6a62d6.png)

**Comment by pastelpalette** [comment]
14:52:49.597
[STDERR]: java.util.concurrent.CompletionException: java.lang.ClassCastException: com.minelittlepony.hdskins.skins.ValhallaSkinServer$AuthHandshake cannot be cast to com.minelittlepony.hdskins.skins.ValhallaSkinServer$AuthResponse
14:52:49.597
[STDERR]: 	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
14:52:49.597
[STDERR]: 	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
14:52:49.597
[STDERR]: 	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
14:52:49.598
[STDERR]: 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source)
14:52:49.598
[STDERR]: 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
14:52:49.598
[STDERR]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
14:52:49.598
[STDERR]: 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
14:52:49.598
[STDERR]: 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
14:52:49.598
[STDERR]: Caused by: java.lang.ClassCastException: com.minelittlepony.hdskins.skins.ValhallaSkinServer$AuthHandshake cannot be cast to com.minelittlepony.hdskins.skins.ValhallaSkinServer$AuthResponse
14:52:49.598
[STDERR]: 	at com.minelittlepony.hdskins.skins.ValhallaSkinServer.authResponse(ValhallaSkinServer.java:179)
14:52:49.598
[STDERR]: 	at com.minelittlepony.hdskins.skins.ValhallaSkinServer.authorize(ValhallaSkinServer.java:157)
14:52:49.598
[STDERR]: 	at com.minelittlepony.hdskins.skins.ValhallaSkinServer.uploadPlayerSkin(ValhallaSkinServer.java:80)
14:52:49.599
[STDERR]: 	at com.minelittlepony.hdskins.skins.ValhallaSkinServer.performSkinUpload(ValhallaSkinServer.java:68)
14:52:49.599
[STDERR]: 	at com.minelittlepony.hdskins.client.SkinUploader.lambda$uploadSkin$0(SkinUploader.java:209)
14:52:49.599
[STDERR]: 	at com.minelittlepony.hdskins.client.SkinUploader$$Lambda$2617/1022070303.run(Unknown Source)
14:52:49.599
[STDERR]: 	... 6 more

**Comment by Sollace** [comment]
Update HD Skins.

**Comment by killjoy1221** [comment]
Already fixed in v6.1.1-mc1.15.2
