### ISSUE TITLE
can't change skin

### ISSUE THREAD

**Issue by krocosofa** [MineLittlePony/HDSkins#32]
![skinfailed](https://user-images.githubusercontent.com/67333367/85431055-aadd5380-b589-11ea-89af-dddba49083cf.png)

When changing the skin, this inscription appears, but the skin does not change, what should I do?

**Comment by krocosofa** [comment]
okay, but how can I join a multiplayer server, sorry for stupid

**Comment by Sollace** [comment]
You have to have a valid Mojang account. aka Buy the game.

**Comment by krocosofa** [comment]
thanks.
