### ISSUE TITLE
Sword is in wrong hand in reflection in the skin manager

### ISSUE THREAD

**Issue by derram** [MineLittlePony/HDSkins#34]
![Selection_869](https://user-images.githubusercontent.com/5730335/91668701-287b8d80-eafe-11ea-8123-97249a1cf6b1.png)

**Comment by Sollace** [comment]
It's not that it's in the wrong hand, it's that the entire body needs to be flipped. It's a very minor visual bug, though, along with how the reflection is not semi-translucent (thanks, Mojang)
