### ISSUE TITLE
No skin server backend docs

### ISSUE THREAD

**Issue by alxpettit** [MineLittlePony/HDSkins#35]
So I'm setting up a custom modpack to play with my friends, and I'd like to be able to have all our skins together on one dedicated server. Is there any documentation on on the skin server protocol so that I can make my own implementation?

**Comment by alxpettit** [comment]
Awesome, thanks! I found specs [here](https://github.com/killjoy1221/ValhallaSkinServer/wiki/Endpoints). I'll try using the flask app as is and maybe mess around with the code a bit for fun. :)

It might be useful to link to this from the README on HDSkins/MineLittlePony for others.

**Comment by killjoy1221** [comment]
You can get a quick list of endpoints from the swagger docs.
https://skins.minelittlepony-mod.com/api/v1/
