### ISSUE TITLE
Suggestion: Armor retexturing

### ISSUE THREAD

**Issue by Heptor44** [MineLittlePony/HDSkins#37]
I like to use a ghost-like skin, and the armor makes the skin almost completely useless, so it'd be nice if I could retexture armor with a skin, or just have a slider with opacity for the armor (with a lower limit higher than 0, as to prevent an advantage.)

**Comment by autumnblazey** [comment]
I see what you mean, but armour is already retextured through resource packs so they conflict with each other

**Comment by killjoy1221** [comment]
It would also be as lot of work for what I see as little gain.
