### ISSUE TITLE
[Basic Quesiton]

### ISSUE THREAD

**Issue by Merith-TK** [MineLittlePony/HDSkins#38]
Is this HDSkins for MineLittlePony... Or HDSKins in general that just happens to support minelittlepony?

**Comment by killjoy1221** [comment]
It's minelittlepony that supports hdskins.

**Comment by Merith-TK** [comment]
> It's minelittlepony that supports hdskins.

Okay, but is this Standalone? Like can i use this, without having Minelittlepony

**Comment by killjoy1221** [comment]
Yes, it is standalone.

**Comment by Merith-TK** [comment]
Alright, thanks
