### ISSUE TITLE
[pre3] Uploading a skin with the skin manager causes a crash

### ISSUE THREAD

**Issue by derram** [MineLittlePony/HDSkins#4]
[latest.log](https://github.com/MineLittlePony/HDSkins/files/3364878/latest.log)

Skin is updated server side despite the crash.

**Comment by Sollace** [comment]
Did the game actually crash, or are these errors in the log? I don't see anything that says the game died there.

**Comment by derram** [comment]
[paste.txt](https://github.com/MineLittlePony/HDSkins/files/3364886/paste.txt)

Yep, tried it a few times and the game crashed each time. This file is a copy paste of the game output, in case something was weird with the log saving.

Also, might be a different issue but the uploaded skin isn't showing in game. Skin is set to a bat pone.

**Comment by Sollace** [comment]
Yeah, that's weird. I've seen the error come up before but I don't know what it is that causes it.

**Comment by derram** [comment]
As for that second thing, custom skin isn't showing up with the hd skins mod removed either. Still just the bat pone solider.

Not sure how to change skins without the skin manager to test for the crash.

**Comment by Sollace** [comment]
You won't see your skin without HD Skins installed. For that you have to upload it to mojang's website.

**Comment by Sollace** [comment]
I'm going to refer this to @killjoy1221 The problem seems to be whatever method they're using to copy images in MineLP, so it's no specific to the skin previewer.

**Comment by Sollace** [comment]
Should be fixed, I think, I hope. I'm going to leave this open until we can get a preview build out to be sure.

https://github.com/MineLittlePony/HDSkins/commit/3d4ac2987cb6102e3110f26bf2a5b3c8a46be7a4

**Comment by killjoy1221** [comment]
[snapshot jar](http://repo.minelittlepony-mod.com.s3.amazonaws.com/maven/snapshot/com/minelittlepony/MineLittlePony/1.14.3-3.3-SNAPSHOT/MineLittlePony-1.14.3-3.3-20190706.200417-38.jar)

**Comment by derram** [comment]
Both problems solved with those snapshots, thanks!

Side note: I had to join a multiplayer server to load my custom skin, was stuck with the bat pone skin  when testing in a SP world. After joining the server my custom skin showed in the SP world as well. Might have something to do with the new skin caching
