### ISSUE TITLE
cant change skin

### ISSUE THREAD

**Issue by zuzu428** [MineLittlePony/HDSkins#41]
how to change pony skin ??i cant change skin ...because it say ( sun.security.provider.certpath.suncertpathbuilderexception: unable to find valid certification path to requested target ) and i dont know what it this??? pls help me !! QWQ

**Comment by Sollace** [comment]
I'm also going to link this issue, as it might be related. https://github.com/MineLittlePony/HDSkins/issues/40

**Comment by zuzu428** [comment]
same no change :( still sun.security.provider.certpath.suncertpathbuilderexACception: unable to find valid certification path to requested target 
even use another version or reinstall ...
