### ISSUE TITLE
Incompatibility with Iris mod.

### ISSUE THREAD

**Issue by RowanSkie** [MineLittlePony/HDSkins#45]
The full details here:

https://github.com/IrisShaders/Iris/issues/489

EDIT: Basically, shader mod seems to be unable to run with Kirin UI/HDSkins.

**Comment by Sollace** [comment]
This appears to be a problem with Iris. They need to ensure their code works when rendering an entity model from the main menu.

No doubt there will be other mods that could cause incompatibilities in the same way.

**Comment by Sollace** [comment]
There doesn't appear to be any public builds of Iris for 1.17.

**Comment by Sollace** [comment]
There doesn't appear to be any public builds of Iris for 1.17. Can you please link me to where you were able to download that mod from?

**Comment by RowanSkie** [comment]
The download is actually seen on its Modrinth page.

**Comment by Sollace** [comment]
Tested the fix with the changes in https://github.com/MineLittlePony/HDSkins/commit/ee78ad6e38695163c827777b642f63d1cbb7ff39 with Iris (both with and without Sodium) and it appears to be resolved. I will be keeping this open, though, as there is an unresolved issue with Iris.

**Comment by RowanSkie** [comment]
You know, I tried the fix with my own compiled build of the latest merge, and it certainly didn't CTD itself out now.

**Comment by RowanSkie** [comment]
Iris and Iris-forked Sodium just updated, which I tested and immediately crashed when I load the HD Skins screen again before world view.

**Comment by Sollace** [comment]
@RowanSkie Did you use the custom buuld of HDSkins that you said was working?

**Comment by RowanSkie** [comment]
Well, it was the latest pull you created after all, but yeah it did.

**Comment by Sollace** [comment]
Tested and appears to be working with the version of iris found on modrinth (over here: https://modrinth.com/mod/iris/version/lAEtBzCu )

**Comment by Sollace** [comment]
Reopening this, as Iris seems to have broken something again.
