### ISSUE TITLE
Can't load any custom skins at all

### ISSUE THREAD

**Issue by NexusTheBrony** [MineLittlePony/HDSkins#47]
As the title says. browse button works, but doesn't load the skin. skins from *both* MineLP and mojang servers refuse to download (in the menu at least). nothing showing up in the logs afaik. i'm on 6.5.0 or whichever is the first version for 1.18
[latest.log](https://github.com/MineLittlePony/HDSkins/files/7654780/latest.log)

**Comment by NexusTheBrony** [comment]
update: skins load perfectly fine in-game, however the skin changing menu will not load anything

**Comment by Sollace** [comment]
Try removing Optifine.

We generally don't support that mod, and fabric users have several alternatives that work better.

**Comment by NexusTheBrony** [comment]
> Try removing Optifine.
> 
> We generally don't support that mod, and fabric users have several alternatives that work better.

would iris (sodium with shaders) be viable?

**Comment by NexusTheBrony** [comment]
![2021-12-06_01 11 51](https://user-images.githubusercontent.com/32724830/144796480-b689ea64-1b39-492f-b00d-861499b8b85f.png)
if it matters this includes iris shaders

and while this does look like a buggy mess, the buttons and skin loading works as it should. should I make this a separate issue?

**Comment by Sollace** [comment]
Iris may have broken support in 1.18 then. You may try with just sodium or go back to Optifine and just accept the preview in the skin manager won't work.

The important thing is, does the skin manager work when you remove Optifine?

**Comment by Sollace** [comment]
Additionally, I didn't notice this before, but you do not appear to have Mine Little Pony installed.

**Comment by NexusTheBrony** [comment]
the skin system works perfectly fine (functionally at least) without optifine, iris or no iris. whether this ui bug is bc of iris idk

as for not having MineLP installed, i'm aware. the skin im wanting to use isn't a MineLP skin, but last i tried u can't upload non-minelp skins with minelp installed


also unrelated: i hav a question i wanna ask in private, but i seem to hav lost u on discord (we shared a server at 1 point)

**Comment by Sollace** [comment]
Okay, cool. So the issue at hoof is a compatibility issue with Iris.

I'll focus on that, then.

> but last i tried u can't upload non-minelp skins with minelp installed

Yes you can, actually. Just upload the skin as normal. It's just that minelp changes the model it renders as into a pony based on the trigger pixels. If you use an image without those pixels, it will appear as a human same as before.

**Comment by Sollace** [comment]
Redirect: https://github.com/MineLittlePony/HDSkins/issues/45

**Comment by Sollace** [comment]
Tested with Iris 1.1.3 from here: https://github.com/IrisShaders/Iris/releases/tag/1.16.x%2Fv1.1.3

I see no issue here. @NexusTheBrony 
![image](https://user-images.githubusercontent.com/6429283/145366955-c62d55a6-74b1-441b-ae76-af18007599d7.png)
