### ISSUE TITLE
Bug while loading with optifine

### ISSUE THREAD

**Issue by MasterShowBlood** [MineLittlePony/HDSkins#48]
![2021-12-26_21 36 49](https://user-images.githubusercontent.com/84067311/147419514-c9b59b4c-55cc-4422-ae0f-7de50fbf80c0.png)
Whenever I try to load HDSkins, it doesn't allow me to load it with Optifine. Is there a way you can patch this? I love having Optifine in my minecraft due to FPS boost.

**Comment by Sollace** [comment]
We don't support optifine. Please use something else.

https://lambdaurora.dev/optifine_alternatives

https://www.curseforge.com/minecraft/mc-mods/sodium
https://irisshaders.net/
