### ISSUE TITLE
Not able to use Alex skin format in custom resource pack

### ISSUE THREAD

**Issue by VioletRose** [MineLittlePony/HDSkins#5]
I could not find a documented way to have a custom resource pack skin use the Alex (3 pixel arms) skin format. If there is a way to do this with a pixel trigger, that information should be added to the documentation. If not, this should either be added, or a new property should be added to the skins.json schema.

**Comment by Sollace** [comment]
Ah, I knew I was forgetting something.

Right now the json doesn't have any method to specify the skin model type, so it's just going to use whatever the player's actual skin is, or the default for their profile.

I'll be sure to add support in the next release.

**Comment by Sollace** [comment]
https://github.com/MineLittlePony/HDSkins/commit/a0220ed2bfae957f76e631ca65d2e4d4b5e1f775
