### ISSUE TITLE
Unable to Upload Skins

### ISSUE THREAD

**Issue by Luka-Nightwind** [MineLittlePony/HDSkins#54]
Per the chat in the Discord putting an issue in here to help mark it down that Uploads to the server via the in-game feature hang indefinitely. 

![](https://cdn.discordapp.com/attachments/362645846493233152/1038976188611317810/image.png)

**Comment by mattmess1221** [comment]
From looking at the skin server logs, I see that only the POST to `/api/v1/auth/handshake` is being made. Something is preventing it from doing the second POST to `/api/v1/auth/response`.

It's probably related to the skin server updates, but I have no idea why this is happening. The schema for logins should have changed in a way that breaks things.

For reference, here is what the handshake endpoint returns. 
```
➜ curl -X POST https://skins.minelittlepony-mod.com/api/v1/auth/handshake -d name=JoyJoy
{"serverId":"O99O60kAMMjiVJHroJzVXs9BMeYqg14ZnJGcC13xsS8","verifyToken":1342852368,"offline":false}
```

**Comment by mattmess1221** [comment]
All issues were fixed server-side.
