### ISSUE TITLE
[snapshot] Default skin is consistently applied instead of custom skin on first join after startup.

### ISSUE THREAD

**Issue by derram** [MineLittlePony/HDSkins#6]
After opening minecraft, the default skin (in my case, bat pone soldier) will be applied when joining a world instead of the set custom skin.

This happens in both multiplayer and single player. 

Disconnecting and reconnecting to the server or exiting and reopening a single player world causes the correct skin to be applied.

**Comment by Sollace** [comment]
Which version are you experiencing this on? Pre-3?

Also which servers did you upload the skin to?

Generally, it should appear immediately after the skin has been loaded for the first time.

**Comment by derram** [comment]
Version is the snapshots from this thread: https://github.com/MineLittlePony/HDSkins/issues/4#issuecomment-508951630

I actually uploaded my skin to all the servers when I was testing things out during this issue: https://github.com/MineLittlePony/HDSkins/issues/4

The default skin sticks around until the rejoin, but after that the skin is loaded instantly as it should.

**Comment by Sollace** [comment]
Can you try deleting the `.minecraft\assets\hd` folder, and then join a single player world and see if your skin loads after that.

Uploading to one skin server is fine. It normally just takes the skin from the first one that responds.

**Comment by derram** [comment]
![Selection_880](https://user-images.githubusercontent.com/5730335/60899165-9f393580-a22f-11e9-8145-cfbd7713357d.png)

Folder doesn't exist.

**Comment by Sollace** [comment]
That's a problem then. It means the cache is not even being used, and you're downloading the skin directly from the server every time you play.

Send us your game output. (latest.log)

**Comment by derram** [comment]
[latest.log](https://github.com/MineLittlePony/HDSkins/files/3373591/latest.log)

**Comment by Sollace** [comment]
Well I don't see anything there that would tell me what's happening...

**Comment by derram** [comment]
Just noticed something. Seems the assets/hd folder is created after the world loads, but deleted when the game launches.

![Selection_881](https://user-images.githubusercontent.com/5730335/60900842-841bf500-a232-11e9-92ab-8f96f03bf70b.png)
![Selection_882](https://user-images.githubusercontent.com/5730335/60900850-88481280-a232-11e9-8488-6261b63eb2ad.png)

**Comment by Sollace** [comment]
It shouldn't do that...

**Comment by Sollace** [comment]
The only way that could happen is if something was explicitely calling `clearSkinCache()` when the game starts. Does it get deleting whilst launching, or only when you open the skins gui?

**Comment by Sollace** [comment]
In fact I realise the only code that _can_ delete that directory, would likely fail because it's not empty.

     * @throws  DirectoryNotEmptyException
     *          if the file is a directory and could not otherwise be deleted
     *          because the directory is not empty <i>(optional specific
     *          exception)</i>

Whatever is happening, it doesn't seem to be us.

**Comment by derram** [comment]
Might be fabric doing it, don't have any other mods installed and I disabled optifabric for these tests.

As far as I can tell, fabric doesn't recursively load mods, but I'll try moving those folders of old mods out and test again.
![Selection_883](https://user-images.githubusercontent.com/5730335/60902850-ef1afb00-a235-11e9-815b-61680aa09501.png)


![Selection_883](https://user-images.githubusercontent.com/5730335/60902753-c2ff7a00-a235-11e9-8dad-079ecaf18dab.png)

**Comment by killjoy1221** [comment]
This could be the launcher's doing. It likes to clean up files from the assets folder that haven't been used.

**Comment by Sollace** [comment]
That could be it. I've been trying the vanilla launcher, though, and I don't get this behaviour. There is also no setting in the launcher that looks like it would cause this.

**Comment by derram** [comment]
Hmm, I am using a pretty old launcher as well.

I'll test that next. 

![Minecraft Launcher 1 6 89-j_884](https://user-images.githubusercontent.com/5730335/60903312-b0397500-a236-11e9-8ddf-11a105348e0e.png)

**Comment by Sollace** [comment]
@derram (Jamey Voice) Now _there's_ your problem.

Did you not get the launcher update(s)? They're free and largely automatic...

**Comment by derram** [comment]
This launcher is from the days long before the linux launcher could update itself, just never really had a reason to update it manually.

After updating, the default skin loaded up initially, but a rejoin again fixed it. This time the custom skin stuck between launches though.

Thanks again!

**Comment by Sollace** [comment]
@derram No prob!

Just a bit of information: Rejoining the world has nothing to do with it. There's a few seconds delay that the server takes to download your skin. If you just continued to play it would have popped up on its own.

**Comment by derram** [comment]
I'd have to test more to see if it happens with the new launcher, but with the old launcher there were times where I noticed the default skin after I'd been playing for over an hour.

Not sure if what the launcher was doing would still be having an affect at that point.
