### ISSUE TITLE
Weird hat appears with the texture of one of the skins I use for mine little pony

### ISSUE THREAD

**Issue by LucynyTheWitch** [MineLittlePony/HDSkins#60]
Whenever I use the Mine Little Pony mod with HD Skins and upload a skin through HD Skins ValhallaSkinServer, the skin is applied along with a weird hat, the hat's texture is the texture of another skin I use sometimes.
Is there any way to fix it or?

**Comment by Sollace** [comment]
Sounds like you accidentally uploaded your skin as a hat texture. In the skinning gui toggle the skin type to the hat type you uploaded before and click "clear" to remove it.
