### ISSUE TITLE
The skin preview gets reset to a generic greyscale pony after opening GUIs inside the skin selection screen

### ISSUE THREAD

**Issue by whitebear60** [MineLittlePony/HDSkins#64]
# Issue Description
The Current Skin window resets to a generic greyscale pony after opening and closing the GUIs using the buttons in the skin selection menu (skin browsing menu and MineLP settings), with "Clearing local player skin cache" message appearing in the console

# Environment
Mine Little Pony 4.10.1
HD Skins 6.10.1
Minecraft 1.20.1

# Steps To Reproduce
1. Open the Skin Manager. Your existing pony skin should load automatically in the Current Skin window
2. Open either the Mine Little Pony Settings or the Skin Browser using either the left-most or the right-most button in the bottom button row.
3. Close either of those windows using the Close button at the bottom, not the Esc key. You should return to the Skin Manager
4. Look at the Current Skin Window.

# Expected Behaviour
The current skin should stay in the Current Skin window

# Actual Behaviour
The current skin seems to be erased from the cache and, therefore, disappears from the GUI

<img src="https://github.com/MineLittlePony/HDSkins/assets/42472132/484a5347-2d17-4375-ac5e-77023a86ffae" width=300> 
<img src="https://github.com/MineLittlePony/HDSkins/assets/42472132/503aafaa-e4cd-4998-b5ad-47ec2716c4f0" width=300>

**Comment by Sollace** [comment]
The skin is fetch from the server. Clearing the local cache has no effect on that (and is intentional behaviour).

Does the skin come back if you close and reopen the main gui? (go back to the main menu and click on the pants button)

**Comment by whitebear60** [comment]
It does return, yes. I mentioned cause I thought that it loads from server into cache and then loads from there, but, well, I don't know for sure how the mod works since I'm not a developer
________________________________

**Comment by whitebear60** [comment]
Here's the demonstration, if that would be relevant
https://github.com/MineLittlePony/HDSkins/assets/42472132/6ce86935-5c31-41e9-80de-83f083add194

**Comment by Sollace** [comment]
This will be fixed as of 1.20.2
