### ISSUE TITLE
Crash : Unexpected error on Quilt

### ISSUE THREAD

**Issue by SoggiestCereal** [MineLittlePony/HDSkins#65]
Using Quilt on 1.20.1 and all my mods work fine, MineLP included, but yet whenever I simply add HDSkins it crashes; I've tried testing it with only the essential mods but it still crashed all the same. I'm not exactly smart enough to deduce what is causing it but I'm only able to assume it's something to do with Quilt itself for some reason? Also I never use Git so hopefully this is correct, and hopefully it's not a random mistake on my part

Crash log: https://pastebin.com/qTDndXwu

**Comment by Sollace** [comment]
This looks to me like you had the wrong version of HDSkins.

You should have this one: https://github.com/MineLittlePony/HDSkins/releases/tag/6.10.2%2B1.20
