### ISSUE TITLE
Alex skin model will not upload.

### ISSUE THREAD

**Issue by AdamDash** [MineLittlePony/HDSkins#69]
After uploading my skin and selecting the Alex option in the preview menu it then shows up as a Steve model instead of an Alex one in both the current skin menu and inside the game in v6.12.3 of HD skins.

https://github.com/MineLittlePony/HDSkins/assets/65252885/810e506d-4543-4610-9652-7a502510b88c

**Comment by Sollace** [comment]
This was fixed in https://github.com/MineLittlePony/HDSkins/commit/88207db6a1bc09da1b9ea5024e450e90a595bb77
