### ISSUE TITLE
Uploading skin failed

### ISSUE THREAD

**Issue by raviolli16** [MineLittlePony/HDSkins#70]
I cannot change my pony's skin despite I downloaded the v1.20.6 of mine little pony, fabric api, kirin and hdskins
![Minecraft_ 1 20 6 5_21_2024 11_26_58 PM](https://github.com/MineLittlePony/HDSkins/assets/170211686/77e27848-3891-401b-b93f-c3b730b110e3)

**Comment by mattmess1221** [comment]
Uploading skins requires you to be capable of joining online servers.
