### ISSUE TITLE
A little question

### ISSUE THREAD

**Issue by Shodelat** [MineLittlePony/HDSkins#71]
Any chance that there will be an update soon that makes it possible to play with my friends on local server on my pirated minecraft?

**Comment by MimzyFang** [comment]
No supporting pirated versions is not planned and will not be considered

If you want to use the mod you need to buy the game

**Comment by Shodelat** [comment]
> No supporting pirated versions is not planned and will not be considered
> 
> If you want to use the mod you need to buy the game

ok thanks for fast reply
