### ISSUE TITLE
Error when uploading skin

### ISSUE THREAD

**Issue by kckarnige** [MineLittlePony/HDSkins#73]
I have tried with normal resolution skins and this error still shows up
I made sure to only use the required mods to make sure it wasn't just a case of "random mod says f*\*\* you"

![image](https://github.com/user-attachments/assets/5358b838-e586-43ff-b874-775c8695db56)

**Comment by mattmess1221** [comment]
This is usually an issue with your DNS provider. Try using [1.1.1.1](https://1.1.1.1).
