### ISSUE TITLE
[BUG] classic skins display as alex model

### ISSUE THREAD

**Issue by Herobrine7707** [MineLittlePony/HDSkins#78]
hi, I have a problem that means I can no longer change my skin with the mod. It shows errors every time I upload it and if the upload does work, it still doesn't change. My pony skin always looks like Fluttershy without it being able to be changed

![Minecraft_ 1 21 1 26 11 2024 11_24_39](https://github.com/user-attachments/assets/316b765b-ec7f-4a98-b6d1-66beb0247a0a)
This skin is displayed without me having uploaded it and I cannot change it even though I have uploaded and selected skins

mine little pony fabric 1.21.1

Step 1: install fabric
Step 2: Install the mod
Step 3: Install HD skins
Step 4: Upload a skin
Step 5: Test it in the game

**Comment by mattmess1221** [comment]
Hi. What error is shown when you try to upload a skin?

**Comment by Herobrine7707** [comment]
There are 3 errors I couldn't upload the skin it said error when uploading then the skin wasn't updated I could fix the 2 somehow just don't ask me how and now I have the error that it isn't textured correctly as my skins have that, strangely enough alex model whether I have steve genomes

**Comment by mattmess1221** [comment]
Can you share your game log?

**Comment by Herobrine7707** [comment]
crash log or normal log?

**Comment by mattmess1221** [comment]
Both if you have them.

**Comment by Herobrine7707** [comment]
OK, but I don't have any crash logs because they are only created when the game crashes. Since it doesn't crash, there aren't any. I don't know exactly which ones I need. I could send the latest log 
[latest.log](https://github.com/user-attachments/files/17920611/latest.log)

**Comment by mattmess1221** [comment]
You need to share the log where you tried to upload a skin. The one you uploaded doesn't show any error.

A screenshot of the error will also work.

**Comment by Herobrine7707** [comment]
![Minecraft_ 1 21 1 - Einzelspieler 26 11 2024 15_12_10](https://github.com/user-attachments/assets/1f8e5793-73d8-4b2d-9f80-456eb3c972d6) 
And my skin is actually set to classic and is still displayed as Alex

**Comment by mattmess1221** [comment]
I see now. The issue isn't related to uploads, but rendering the wrong model.

For reference, you can see your skin data via https://skins.minelittlepony-mod.com/api/v1/user/ba2fabb6-4bbb-4745-a713-1924ee6d5877

**Comment by Herobrine7707** [comment]
OK and how do you fix that

**Comment by Herobrine7707** [comment]
By the way, some skins are completely broken, it looks like this  
![Minecraft_ 1 21 1 27 11 2024 13_20_39](https://github.com/user-attachments/assets/f7188b99-e5a5-40e6-a072-6f683a174d10)
please fix because I don't know how to fix it

**Comment by Sollace** [comment]
> I see now. The issue isn't related to uploads, but rendering the wrong model.
> 
> For reference, you can see your skin data via https://skins.minelittlepony-mod.com/api/v1/user/ba2fabb6-4bbb-4745-a713-1924ee6d5877

Where is the model attribute?

If the server doesn't specify either "default" or "slim" the client will decide based on the player's UUID.

**Comment by mattmess1221** [comment]
The auto-picking based on UUID should only apply if there's no skin at all. The model for all uploaded skins should be "default" unless specified.

**Comment by Sollace** [comment]
I've released an update to HDSkins to fix this.

https://github.com/MineLittlePony/HDSkins/releases/tag/6.14.1%2B1.21.3

**Comment by Herobrine7707** [comment]
ok but unfortunately it is for 1.21.3 I need it for 1.21.1

**Comment by Sollace** [comment]
> ok but unfortunately it is for 1.21.3 I need it for 1.21.1

https://github.com/MineLittlePony/HDSkins/releases/tag/6.14.1%2B1.21
