### ISSUE TITLE
Elytra don't render with cape resource pack

### ISSUE THREAD

**Issue by Venaf** [MineLittlePony/HDSkins#8]
When using a resource pack with a skins.json specifying a cape for a player, and then elytra are equipped, neither displays.  Removing the elytra restores the cape, removing the resource pack restores the elytra when it's equipped.
[CMC Cape 2.zip](https://github.com/MineLittlePony/HDSkins/files/3403816/CMC.Cape.2.zip)

**Comment by Venaf** [comment]
Not a bug, apparently, Elytra textures share the file with cape textures

**Comment by Sollace** [comment]
Eeyup. Confirmed not a bug.

Here is a new resourcepack that should render elytras.
[CMC.zip](https://github.com/MineLittlePony/HDSkins/files/3406250/CMC.zip)
